[api]
require_key = false
key = ""

[rate_limiting]
enabled = false
requests_per_minute = 100
burst_size = 10

[authentication]
session_timeout = 3600
max_concurrent_sessions = 5

[cors]
allow_credentials = true
max_age = 86400
