[server]
host = "127.0.0.1"
port = 8081
workers = 24

[websocket]
max_connections = 1000
heartbeat_interval = 30
message_size_limit = 1048576

[cors]
allowed_origins = [
    "http://localhost:3000",
    "http://localhost:1420",
    "http://localhost:5173",
    "http://127.0.0.1:1420",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://tauri.localhost",
    "tauri://localhost",
    "http://tauri.localhost",
    "https://tauri.localhost",
    "*"
]
allowed_methods = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]
allowed_headers = ["*"]

[limits]
max_rooms = 1000
max_users_per_room = 50
connection_timeout = 300
